### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by Riipperino** [XxFri3ndlyxX/esx_illegal_drugs#3]
Im getting some error codes when i open F8 
https://gyazo.com/a73791f87a010cc207157bb084d6aadf

See screenshot , the script seems to work but i have no idea why its showing errors

**Comment by XxFri3ndlyxX** [comment]
Looks like you attempted to hide the map icon.  You did it the wrong way.

**Comment by XxFri3ndlyxX** [comment]
Show me your config.lua upload it here.

**Comment by Riipperino** [comment]
`Config              = {}
Config.MarkerType   = -1
Config.DrawDistance = 100.0
Config.ZoneSize     = {x = 5.0, y = 5.0, z = 5.0}
Config.MarkerColor  = {r = 0, g = 255, b = 0}

Config.RequiredCopsCoke  = 2
Config.RequiredCopsMeth  = 1
Config.RequiredCopsWeed  = 0
Config.RequiredCopsOpium = 2

Config.TimeToFarmWeed     = 3  * 1000
Config.TimeToProcessWeed  = 3  * 1000
Config.TimeToSellWeed     = 3  * 1000

Config.TimeToFarmOpium    = 3  * 1000
Config.TimeToProcessOpium = 3  * 1000
Config.TimeToSellOpium    = 3  * 1000

Config.TimeToFarmCoke     = 3  * 1000
Config.TimeToProcessCoke  = 3  * 1000
Config.TimeToSellCoke     = 3  * 1000

Config.TimeToFarmMeth     = 3  * 1000
Config.TimeToProcessMeth  = 3  * 1000
Config.TimeToSellMeth     = 3  * 1000

Config.Locale = 'en'

Config.Zones = {
	CokeField =			{x=-99.31,  y=1908.26,  z=197.09},
	CokeProcessing =	{x=1093.1,  y=-3194.85,  z=-38.99},
	CokeDealer =		{x=-1610.85,   y=-3016.73,   z=-75.21},
	MethField =			{x=1005.721,   y=-3200.301,  z=-38.519},
	MethProcessing =	{x=1014.878, y=-3194.871,  z=-38.993},
	MethDealer =		{x=-800.06,     y=183.52,   z=72.6},
	WeedField =			{x=1057.448,  y=-3197.646,  z=-39.138},
	WeedProcessing =	{x=1037.527,  y=-3205.368,  z=-38.17},
	WeedDealer =		{x =-1172.28,   y =-1572.02,  z= 4.66},
	OpiumField =		{x=2433.804,  y=4969.196,   z=42.348},
	OpiumProcessing =	{x=1388.91,   y=3605.44,    z=38.94},
	OpiumDealer =		{x=-800.17, y=186.28,   z=72.6}
}


`

Sorry for late reply but here u got mate =)

**Comment by XxFri3ndlyxX** [comment]
Well like i said you did not properly disable map. You shouldn't remove code you if you don't understand how it works.  Here download this https://github.com/XxFri3ndlyxX/esx_illegal_drugs/releases/tag/v1.0.4
