### ISSUE TITLE
unable to get locations to work

### ISSUE THREAD

**Issue by Takima80** [XxFri3ndlyxX/esx_illegal_drugs#5]
installed mod and then went to check out the locations on the map and there isn't anything to do at those locations.

**Comment by XxFri3ndlyxX** [comment]
Just tested it on a fresh server and works fine. Read the readme.

**Comment by Takima80** [comment]
I did everything in the readme file the first time around: 
REQUIREMENTS This version is modified to use FiveMIPL
You will also need Teleport Script
You will also need the latest esx_policejob & latest es_extended

INSTALLATION
Put resource esx_illegal_drugs in your server Import esx_illegal_drugs.sql in your database
Add this in your server.cfg:
start esx_illegal_drugs

Still only thing that shows up are the map markers.  There isn't anything when i go to the location.  Its an empty parking lot!

**Comment by lowheartrate** [comment]
I also have this issue correctly that I can't see any entrance markers and it does not prompt me with anything when I go an `/tp` to the entrance coordinates.
